# Generated by Django 3.2.6 on 2021-08-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210821_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/default_image.jpg', upload_to='media'),
        ),
    ]
