# Generated by Django 3.2.6 on 2021-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_snippet_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='copied',
            new_name='copy_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This user has not entered a bio', max_length=400, null=True),
        ),
    ]
